# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pay',
            new_name='Orders',
        ),
    ]
